/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governerContractSol from "./GovernerContract.sol";
export type { governerContractSol };
export type { TimeLock } from "./TimeLock";
